### ISSUE TITLE
results.json file occasionally written empty

### ISSUE THREAD

**Issue by jasongardnerlv** [testophobia/testophobia#51]
Sometimes when there's a failure during a test run, the viewer will be launched and then die with the error:
```
😱 Starting Testophobia...
✔  Testing Complete [119 passed | 1 failed]
   Test Failure: ... (...) ...
🔍 Testophobia Viewer served on port 8090
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at exports.serveViewer (.../testophobia/lib/utils/serve-viewer.js:12:28)
    at Viewer.launchViewer (.../testophobia/lib/Viewer.js:31:5)
    at Viewer.run (.../testophobia/lib/Viewer.js:26:39)
```
The error is the byproduct of the results.json file being empty for some reason.

**Comment by jasongardnerlv** [comment]
This should hopefully be resolved as part of #66
